/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supercalculadora.java;

/**
 *
 * @author USUARIO
 */
public class SuperCaluladoraSwing extends javax.swing.JFrame {

    /**
     * Creates new form SuperCaluladoraSwing
     */
    public SuperCaluladoraSwing() {
        initComponents();
        panresultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textovalor = new javax.swing.JSpinner();
        BOTAOCALCULAR = new javax.swing.JButton();
        panresultado = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lerdivisao2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lerelevadocubo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lerraizquadrada = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lerraizcubica = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lervalorabsoluto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SUPER CALCULADORA");

        jLabel2.setText("INFORME UM VALOR");

        textovalor.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        textovalor.setAlignmentX(1.0F);
        textovalor.setAlignmentY(1.0F);

        BOTAOCALCULAR.setText("CALCULAR");
        BOTAOCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOCALCULARActionPerformed(evt);
            }
        });

        jLabel4.setText("dividir resto por 2");

        lerdivisao2.setForeground(new java.awt.Color(255, 51, 51));
        lerdivisao2.setText("0");

        jLabel8.setText("elevado ao cubo");

        lerelevadocubo.setForeground(new java.awt.Color(255, 51, 51));
        lerelevadocubo.setText("0");

        jLabel12.setText("raiz quadrada");

        lerraizquadrada.setForeground(new java.awt.Color(255, 51, 51));
        lerraizquadrada.setText("0");

        jLabel14.setText("raiz cubica");

        lerraizcubica.setForeground(new java.awt.Color(255, 51, 51));
        lerraizcubica.setText("0");

        jLabel16.setText("valor absoluto");

        lervalorabsoluto.setForeground(new java.awt.Color(255, 51, 51));
        lervalorabsoluto.setText("0");

        javax.swing.GroupLayout panresultadoLayout = new javax.swing.GroupLayout(panresultado);
        panresultado.setLayout(panresultadoLayout);
        panresultadoLayout.setHorizontalGroup(
            panresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panresultadoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panresultadoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lervalorabsoluto))
                    .addGroup(panresultadoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lerraizcubica))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panresultadoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lerraizquadrada))
                    .addGroup(panresultadoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lerelevadocubo))
                    .addGroup(panresultadoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(lerdivisao2)))
                .addGap(62, 62, 62))
        );
        panresultadoLayout.setVerticalGroup(
            panresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panresultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lerdivisao2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lerelevadocubo))
                .addGap(18, 18, 18)
                .addGroup(panresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lerraizquadrada))
                .addGap(18, 18, 18)
                .addGroup(panresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lerraizcubica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lervalorabsoluto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textovalor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BOTAOCALCULAR))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textovalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTAOCALCULAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panresultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTAOCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOCALCULARActionPerformed
        // TODO add your handling code here:
        int valor = Integer.parseInt(textovalor.getValue().toString());
        int divisao2 = valor % 2;
        lerdivisao2.setText(Integer.toString(divisao2));
         
        double elevcubo = Math.pow(valor, 3);
        lerelevadocubo.setText(Double.toString(elevcubo));
        
        double raizcubica = Math.cbrt(valor);
        lerraizcubica.setText(Double.toString(raizcubica));
        
        double raizquadrada = Math.sqrt(valor);
        lerraizquadrada.setText(Double.toString(raizquadrada));
        
        double valorabsoluto = Math.abs(valor);
        lervalorabsoluto.setText(Double.toString(valorabsoluto));
        
       panresultado.setVisible(true);
        
    }//GEN-LAST:event_BOTAOCALCULARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperCaluladoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperCaluladoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperCaluladoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperCaluladoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperCaluladoraSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAOCALCULAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lerdivisao2;
    private javax.swing.JLabel lerelevadocubo;
    private javax.swing.JLabel lerraizcubica;
    private javax.swing.JLabel lerraizquadrada;
    private javax.swing.JLabel lervalorabsoluto;
    private javax.swing.JPanel panresultado;
    private javax.swing.JSpinner textovalor;
    // End of variables declaration//GEN-END:variables
}
