/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagens;

import java.awt.Font;

/**
 *
 * @author USUARIO
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
        lerfrase.setText("<html>Vou pensar em um valor entre 1 e 5, tente adivinhar!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lerfrase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textovalor = new javax.swing.JSpinner();
        botaopalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lerfrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lerfrase.setText("FRASE");
        lerfrase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lerfrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\images 2.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 270, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\images.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 220, -1));

        jLabel4.setText("VALOR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        textovalor.setModel(new javax.swing.SpinnerNumberModel(1, null, 5, 1));
        getContentPane().add(textovalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        botaopalpite.setText("PALPITE");
        botaopalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(botaopalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaopalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopalpiteActionPerformed
        // TODO add your handling code here:
       double n = 1 + Math.random() * (6 - 1);
       int valor = (int) n;
        System.out.println(valor);
        
        int num = Integer.parseInt(textovalor.getValue().toString());
        
        String f1 = "acertou";
        String f2 = "<html>Errou! Eu pensei no valor " + valor + "</html>"; 
        
        String res = (valor == num)?f1:f2;
        
        lerfrase.setFont(new Font("Arial Black", Font.PLAIN, 12));
        
        lerfrase.setText(res);
    }//GEN-LAST:event_botaopalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaopalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lerfrase;
    private javax.swing.JSpinner textovalor;
    // End of variables declaration//GEN-END:variables
}
